CREATE TABLE "articles" (
  "id_article" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "titre" varchar,
  "sous_titre" varchar,
  "date" date,
  "source" varchar,
  "lien" varchar,
  "moderateur" varchar
);

CREATE TABLE "themes" (
  "id_theme" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "article_id" int,
  "theme" varchar
);

CREATE TABLE "sous_themes" (
  "id_sous_themes" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "theme_id" int,
  "sous_theme" varchar
);

ALTER TABLE "themes" ADD FOREIGN KEY ("article_id") REFERENCES "articles" ("id_article");

ALTER TABLE "sous_themes" ADD FOREIGN KEY ("theme_id") REFERENCES "themes" ("id_theme");
